[project]
name = "petri-watchline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bobby Faber", email = "bfaber@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "snakes>=0.9.33",
]

[project.scripts]
petri-watchline = "petri_watchline:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
